from .base_endpoint import BaseEndpoint


from .entity.camera_availability import CameraAvailability
from .entity.contract import Contract
from .entity.contract_stage import ContractStage
from .entity.event_type import EventType
from .entity.existence_type import ExistenceType
from .entity.mobile_operator import MobileOperator
from .entity.region import Region
from .entity.user_logs import UserLogs
from .entity.vehicle import Vehicle
from .entity.vehicle_error import VehicleError
from .entity.vehicle_camera_error import VehicleCameraError
from .entity.vehicle_camera_status import VehicleCameraStatus
from .entity.vehicle_camera import VehicleCamera
from .entity.vehicle_contract_binding_to_stage import VehicleContractBindingToStage
from .entity.vehicle_contract_binding import VehicleContractBinding
from .entity.vehicle_information import VehicleInformation
from .entity.vehicle_part_type import VehiclePartType
from .entity.vehicle_part import VehiclePart
from .entity.vehicle_status import VehicleStatus
from .entity.vehicle_template_camera import VehicleTemplateCamera
from .entity.vehicle_template_part import VehicleTemplatePart
from .entity.vehicle_template import VehicleTemplate
from .entity.vehicle_to_attached_file import VehicleToAttachedFile
from .entity.vehicle_to_stage import VehicleToStage
from .entity.vehicle_type import VehicleType
from .vehicle_file import VehicleFile
from .vehicle_image import VehicleImage
from .immovable_file import ImmovableFile
from .immovable_image import ImmovableImage
